# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

install:
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - set PATH=C:\jruby-9.0.0.0\bin;%PATH%
  - gem install rake
  
build_script:
  - appveyor AddCompilationMessage "Starting Build"
  - ruby -v
  - cd C:\projects\logstash
  - rake test:install-core

test_script:
  - rake test:core

