# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

install:
  - bundle install
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - appveyor DownloadFile https://s3.amazonaws.com/jruby.org/downloads/1.7.25/jruby-bin-1.7.25.zip
  - 7z x jruby-bin-1.7.21.zip -y > nul
  - SET PATH=C:\projects\logstash\jruby-1.7.25\bin;%PATH%
  
build_script:
  - appveyor AddCompilationMessage "Starting Build"
  - ruby -v
  - cd C:\projects\logstash
  - rake bootstrap

test_script:
  - rake test:core 
