# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  
build_script:
  - rake test:install-core

test_script:
  - rake test:core   